version: "3"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DATABASE_PASSWORD:-yourStrong(!)Password}
    ports:
      - ${DATABASE_PORT:-1433}:1433
    restart: always

  api:
    build:
      context: ./web-api
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    environment:
      - DATABASE_HOST=sqlserver
      - DATABASE_PORT=1433
      - DATABASE_USERNAME=sa
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-yourStrong(!)Password}
      - DATABASE_NAME=${DATABASE_NAME:-lead_test}
      - CREATE_TABLE=${CREATE_TABLE:-True}
      - API_HOST=0.0.0.0
      - API_PORT=5050
      - FLASK_ENV=development
    # command: uwsgi --http 0.0.0.0:5050 --master -p 1 -w entrypoints.flask_app:app
    command: python src/entrypoints/flask_app.py
    restart: always

  data_generator:
    build:
      context: ./web-api
      dockerfile: Dockerfile
    depends_on:
      - api
    environment:
      - DATABASE_HOST=sqlserver
      - DATABASE_PORT=1433
      - DATABASE_USERNAME=sa
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-yourStrong(!)Password}
      - DATABASE_NAME=${DATABASE_NAME:-lead_test}
      - CREATE_TABLE=${CREATE_TABLE:-True}
      - API_HOST=0.0.0.0
      - API_PORT=5050
      - GENERATOR_FREQUENCY=${GENERATOR_FREQUENCY:-10}
    command: python src/entrypoints/populate_database.py
    restart: always

  app:
    depends_on:
        - api
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - 8080:80
    restart: always