version: "3"

services:

  eventstore:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=${EVENT_STORE_HTTP_PORT:-2113}
      - EVENTSTORE_INSECURE=true  
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true 
    ports:
      - ${EVENT_STORE_HTTP_PORT:-2113}:${EVENT_STORE_HTTP_PORT:-2113}


  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DATABASE_PASSWORD:-yourStrong(!)Password}
    ports:
      - ${DATABASE_PORT:-1433}:${DATABASE_PORT:-1433}
    restart: always

  api:
    build:
      context: ./web-api
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
      - eventstore
    environment:
      - DATABASE_HOST=sqlserver
      - DATABASE_PORT=${DATABASE_PORT:-1433}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-sa}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-yourStrong(!)Password}
      - DATABASE_NAME=${DATABASE_NAME:-lead_test}
      - CREATE_TABLE=${CREATE_TABLE:-True}
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=${API_PORT:-5050}
      - EVENT_STORE_HOST=eventstore
      - EVENT_STORE_HTTP_PORT=${EVENT_STORE_HTTP_PORT:-2113}
      - FLASK_ENV=production
    command: python src/entrypoints/flask_app.py
    # command: uwsgi --http 0.0.0.0:${API_PORT:-5050} --master -p 4 -w entrypoints.flask_app:app
    ports:
      - 5050:${API_PORT:-5050}
    deploy:
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s

  data_generator:
    build:
      context: ./web-api
      dockerfile: Dockerfile
    depends_on:
      - api
    environment:
      - DATABASE_HOST=sqlserver
      - DATABASE_PORT=${DATABASE_PORT:-1433}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-sa}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-yourStrong(!)Password}
      - DATABASE_NAME=${DATABASE_NAME:-lead_test}
      - CREATE_TABLE=${CREATE_TABLE:-True}
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=${API_PORT:-5050}
      - GENERATOR_FREQUENCY=${GENERATOR_FREQUENCY:-10}
    command: python src/entrypoints/populate_database.py
    deploy:
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s

  app:
    depends_on:
        - api
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - 8080:80
    deploy:
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s