version: "3"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DATABASE_PASSWORD:-password123}
    ports:
      - ${DATABASE_PORT:-1433}:${DATABASE_PORT:-1433}
    restart: always

  api:
    build:
      context: ./web-api
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    environment:
      - DATABASE_HOST=sqlserver
      - DATABASE_PORT=${DATABASE_PORT:-1433}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-sa}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-password123}
      - DATABASE_NAME=${DATABASE_NAME:-lead_test}
      - CREATE_TABLE=${CREATE_TABLE:-False}
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=${API_PORT:-5050}
      - FLASK_ENV=${FLASK_ENV:-development}
    command: python src/entrypoints/flask_app.py
    ports:
      - 5050:${API_PORT:-5050}
    deploy:
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s

  data_generator:
    build:
      context: ./web-api
      dockerfile: Dockerfile
    depends_on:
      - api
    environment:
      - DATABASE_HOST=sqlserver
      - DATABASE_PORT=${DATABASE_PORT:-1433}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-sa}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-password123}
      - DATABASE_NAME=${DATABASE_NAME:-lead_test}
      - CREATE_TABLE=${CREATE_TABLE:-False}
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=${API_PORT:-5050}
      - GENERATOR_FREQUENCY=${GENERATOR_FREQUENCY:-10}
    command: python src/entrypoints/populate_database.py
    deploy:
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s

  app:
    depends_on:
        - api
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - 8080:80
    deploy:
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s